### PR TITLE
Added Alpine Linux to distro whitelist

### PR DESCRIPTION
**Pull request by justinlime**

### CODE REVIEW

**Review by imindMan — COMMENTED** [review]
Good Alpine :)))

**Comment by logicguy1** [comment]
@imindMan did you make this command?

**Comment by imindMan** [comment]
No I didnt

**Comment by justinlime** [comment]
> @imindMan did you make this command?

It's my command 😈

**Comment by logicguy1** [comment]
Awesome, does the program automatically add the roles?

**Comment by justinlime** [comment]
> Awesome, does the program automatically add the roles?

If the role doesn't exist it will add them :)

**Pull request merged**
