### PR TITLE
add connection configuration to sql.py

### PR DESCRIPTION
**Pull request by timelessnesses**
**What kind of change does this PR introduce?**  
Update

**Describe the changes proposed in the pull request**  
Add support of connection can be configured through .env

**What is the current behavior?**  
it just force us to open port 3336 with root and no password
**What is the new behavior**  
you should be able to customize this, make it more secure

**Does this PR introduce a breaking change?**  
change your configuration. please read .env.example

**Does this PR introduce changes to the database?**
no

**Other information:**

### CODE REVIEW

**Comment by logicguy1** [comment]
#112

**Comment by timelessnesses** [comment]
@logicguy1 this pr introduce much more better configuration and security so yeah.
also haven't tested this so yeah.

**Comment by logicguy1** [comment]
`Config.mysql_database` is not used with the create statements

**Comment by timelessnesses** [comment]
it does being used in connection?

**Comment by timelessnesses** [comment]
tested this and it works

**Comment by timelessnesses** [comment]
with some concerns of why is it defaulting to discox instead of Dev's customized db name

**Comment by logicguy1** [comment]
You sure about this? I'm scared the create statements will fail

**Comment by timelessnesses** [comment]
you could try test it

> .Message ID: ***@***.***>
>

**Pull request merged**
