### PR TITLE
Fix English mistakes in role choosing menus and in command descriptions

### PR DESCRIPTION
**Pull request by jtbx**
**What kind of change does this PR introduce?**  
Spelling and grammar fixes

**Describe the changes proposed in the pull request**  
I fixed some spelling and English issues that were present in the role choosing menus, and in command descriptions shown in v!help

**What is the current behavior?**  
English issues in role choosing menus and in command descriptions shown in v!help

**What is the new behavior**  
No more spelling/grammar mistakes yay

**Does this PR introduce a breaking change?**  
No

**Does this PR introduce changes to the database?**
No

**Other information:**

### CODE REVIEW

**Comment by timelessnesses** [comment]
minor spelling mistakes 😭

**Review by timelessnesses — APPROVED** [review]
reviewed this and description is making much more sense now

**Comment by justinlime** [comment]
LGTM

**Comment by logicguy1** [comment]
Cant merge due to merge conflicts in minecraft.py :sob:

**Comment by jtbx** [comment]
Fixed the merge conflict

**Pull request merged**
